require 'rubygems'
require 'selenium-webdriver'
require 'chunky_png'
require 'open-uri'
require 'rbconfig'
require 'rspec/expectations'
include RbConfig
include RSpec::Matchers
require 'net/http'
require 'uri'
require 'capybara/cucumber'
require 'rspec'
# require 'capybara-webkit'
require 'capybara-screenshot/cucumber'
require 'capybara-screenshot/rspec'